// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Prever_valor_de_casasML.Model
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("price"), LoadColumn(1)]
        public float Price { get; set; }


        [ColumnName("bedrooms"), LoadColumn(2)]
        public float Bedrooms { get; set; }


        [ColumnName("bathrooms"), LoadColumn(3)]
        public float Bathrooms { get; set; }


        [ColumnName("sqft_lot"), LoadColumn(4)]
        public float Sqft_lot { get; set; }


        [ColumnName("floors"), LoadColumn(5)]
        public float Floors { get; set; }


    }
}
